sudo: required
services:
  - docker

before_install:
  - docker build -t czanella/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true czanella/react-test npm test

after_success:
  - docker build -t czanella/fibo-client ./client
  - docker build -t czanella/fibo-nginx ./nginx
  - docker build -t czanella/fibo-server ./server
  - docker build -t czanella/fibo-worker ./worker
  # LOG TO DOCKER HUB
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # PUSH TO DOCKER HUB
  - docker push czanella/fibo-client
  - docker push czanella/fibo-nginx
  - docker push czanella/fibo-server
  - docker push czanella/fibo-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: fibonacci-docker
  env: FibonacciDocker-env
  bucket_name: elasticbeanstalk-us-east-1-898151676259
  bucket_path: fibonacci-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY